"""outpass rejection JSONB column

Revision ID: 0d4070980edb
Revises: 92796691db2b
Create Date: 2023-05-23 01:58:42.515566

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0d4070980edb"
down_revision = "92796691db2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outpass",
        sa.Column("rejection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.execute("UPDATE outpass SET rejection='{}'")
    op.alter_column("outpass", "rejection", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outpass", "rejection")
    # ### end Alembic commands ###
