"""migration_message

Revision ID: 394be623d8ed
Revises: 0d4070980edb
Create Date: 2023-05-27 07:25:27.622964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394be623d8ed'
down_revision = '0d4070980edb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
