"""warden id compulsory in outpass

Revision ID: 3e31d55de436
Revises: ea469b6db3e1
Create Date: 2023-05-03 02:24:28.739834

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e31d55de436"
down_revision = "ea469b6db3e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("outpass", "warden_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("outpass", "warden_id", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
