"""outpass out_time

Revision ID: 92796691db2b
Revises: dde67db9ca3c
Create Date: 2023-05-21 00:31:47.449271

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "92796691db2b"
down_revision = "dde67db9ca3c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "outpass", "out_time", existing_type=postgresql.TIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "outpass", "out_time", existing_type=postgresql.TIME(), nullable=False
    )
    # ### end Alembic commands ###
