"""models

Revision ID: 980626dfe77c
Revises: 
Create Date: 2023-04-30 12:22:45.245893

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "980626dfe77c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("roll_number", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("account_type", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column(
            "academic_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "hostel_details", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx__auth_roll_number", "auth_user", ["roll_number"], unique=False)
    op.create_index("idx__auth_user_email", "auth_user", ["email"], unique=False)
    op.create_index(
        "idx__auth_user_first_name", "auth_user", ["first_name"], unique=False
    )
    op.create_index(
        "idx__auth_user_last_name", "auth_user", ["last_name"], unique=False
    )
    op.create_index("idx__auth_uuid", "auth_user", ["uuid"], unique=False)
    op.create_table(
        "guardian",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("phone_number", sa.BigInteger(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outpass",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("out_date", sa.Date(), nullable=False),
        sa.Column("out_time", sa.Time(), nullable=False),
        sa.Column("expected_return_at", sa.Date(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("alternate_phone_number", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("exited_at", sa.DateTime(), nullable=True),
        sa.Column("returned_at", sa.DateTime(), nullable=True),
        sa.Column("warden_message", sa.String(), nullable=True),
        sa.Column("approval", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx__outpass_out_date", "outpass", ["out_date"], unique=False)
    op.create_index("idx__outpass_status", "outpass", ["status"], unique=False)
    op.create_index("idx__outpass_uuid", "outpass", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx__outpass_uuid", table_name="outpass")
    op.drop_index("idx__outpass_status", table_name="outpass")
    op.drop_index("idx__outpass_out_date", table_name="outpass")
    op.drop_table("outpass")
    op.drop_table("guardian")
    op.drop_index("idx__auth_uuid", table_name="auth_user")
    op.drop_index("idx__auth_user_last_name", table_name="auth_user")
    op.drop_index("idx__auth_user_first_name", table_name="auth_user")
    op.drop_index("idx__auth_user_email", table_name="auth_user")
    op.drop_index("idx__auth_roll_number", table_name="auth_user")
    op.drop_table("auth_user")
    # ### end Alembic commands ###
