"""guardian phone number

Revision ID: a7b172698579
Revises: de9de7fa3192
Create Date: 2023-05-01 06:58:28.457337

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a7b172698579"
down_revision = "de9de7fa3192"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guardian", "phone_number", existing_type=sa.BigInteger(), type_=sa.String()
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guardian", "phone_number", existing_type=sa.String(), type_=sa.BigInteger()
    )
    pass
    # ### end Alembic commands ###
