"""outpass datetime

Revision ID: dde67db9ca3c
Revises: 3e31d55de436
Create Date: 2023-05-07 05:21:04.996222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dde67db9ca3c"
down_revision = "3e31d55de436"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "outpass", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "outpass", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outpass", "updated_at")
    op.drop_column("outpass", "created_at")
    # ### end Alembic commands ###
