"""guardian id in outpass

Revision ID: ea469b6db3e1
Revises: a7b172698579
Create Date: 2023-05-03 02:19:32.301362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea469b6db3e1'
down_revision = 'a7b172698579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outpass', sa.Column('guardian_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'outpass', 'guardian', ['guardian_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outpass', type_='foreignkey')
    op.drop_column('outpass', 'guardian_id')
    # ### end Alembic commands ###
